FROM node:22.16.0-alpine3.17 AS base

FROM base AS development

WORKDIR /app

COPY package.json .

RUN npm install

COPY . .

CMD ["npm", "run", "dev"]

EXPOSE 3000

FROM base AS production

WORKDIR /app

COPY package.json .

RUN npm install --only=production

COPY . .

RUN npm run build

CMD ["npm", "run", "start"]

EXPOSE 5000