# ---------- Base image ----------
FROM node:18-alpine AS base
WORKDIR /app

# ---------- Development stage ----------
FROM base AS development
COPY package*.json .
RUN npm install
COPY . .
CMD ["npm", "run", "dev"]
EXPOSE 3000

# ---------- Build stage ----------
FROM base AS builder
COPY package.json package-lock.json* ./
RUN npm install
COPY . .
RUN npm run build

# Remove dev dependencies to slim the build before copying
RUN npm prune --production

# ---------- Production stage ----------
FROM node:22.16.0-alpine AS production
COPY --from=builder /app/package.json ./
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/.next ./.next
COPY --from=builder /app/public ./public
CMD ["npm", "run", "start"]
EXPOSE 3000
